<?php

namespace AppBundle\Repository;

/**
 * WerknemersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WerknemersRepository extends \Doctrine\ORM\EntityRepository
{
}
